services:
  - type: web
    name: videocalling-interview-platform
    env: node
    plan: free
    buildCommand: |
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
